### ISSUE TITLE
Please add a license & consider renaming the repository

### ISSUE THREAD

**Issue by unixorn** [xVanjaZ/xVanjaZ-ZSH-Theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

Also, please consider renaming the repository to something less generic than ZSH-Theme - xvanjaz-zsh-theme would be easier for other people to keep track of in their ZSH configurations.

**Comment by xVanjaZ** [comment]
Hey there, 

I added a licence and changed the name. Please do as you wish!

**Comment by unixorn** [comment]
That was quick!

I'm adding a link to this in the tutorials section of [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) in https://github.com/unixorn/awesome-zsh-plugins/pull/695 since it's a nice little oh-my-zsh+iTerm2 QuickStart.
